services:
  bot:
    # Pull pre-built image from Docker Hub
    image: lutogin/go-motivation:latest
    container_name: go-motivation-bot
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
